### PR TITLE
GDAX update

### PR DESCRIPTION
**Pull request by lawrencegs**
Hi guys, now that Coinbase Exchange is GDAX, I put this pull request to swiftly update exchange.coinbase.com to gdax.com. There are still some reference to Coinbase Exchange that the repo admin should decide though (e.g the library name).

### CODE REVIEW

**Comment by mihar** [comment]
LGTM

**Comment by mihar** [comment]
Our plan is to rename this repo and release a new package with the name `gdax`. All future development would only be pushed as the `gdax` package.

**Comment by tristanlang** [comment]
@mihar do you have an estimate for when the `gdax` package will be released / when the `coinbase-exchange` package will be deprecated?

**Comment by mihar** [comment]
@tristanjlang, the transition has now been complete. 

The new package is [gdax](https://www.npmjs.com/package/gdax) and the new repository is [gdax-node](https://github.com/coinbase/gdax-node).

**Pull request merged**
